# Generated by Django 4.2.16 on 2025-12-30 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizConfigUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quiz_configs/uploads/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('quiz_date', models.DateField(blank=True, null=True)),
                ('quiz_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Quiz Config Upload',
                'verbose_name_plural': 'Quiz Config Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
