# Generated by Django 4.2.16 on 2025-12-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizconfigupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquiz',
            name='background_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
